FROM gcr.io/distroless/base-debian13:nonroot@sha256:0896741ba5bafd3ac87ea025a5f578952f2d238ddc3614cb368acc983a687aa2

# Set working directory
WORKDIR /app

# Copy the native executable and set permissions
COPY --chown=65532:65532 --chmod=0555 target/*-runner /app/application

ENV QUARKUS_HTTP_HOST=0.0.0.0
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Expose the default Quarkus port
EXPOSE 8080

# Run as non-root user
USER 65532:65532

ENTRYPOINT ["/app/application"]
