// Icon components generated by unplugin-icons
// Only the icons used in the application are bundled

// Clock icon: inline SVG instead of fa6-regular (saves ~300KB bundle size)
const IconClock = {
  name: 'IconClock',
  template: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-1em h-1em" fill="currentColor" preserveAspectRatio="xMidYMid meet"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 256a24 24 0 1 1 48 0 24 24 0 1 1 -48 0zM256 96a24 24 0 1 1 0-48 24 24 0 1 1 0 48zm96 136a24 24 0 1 1 48 0 24 24 0 1 1 -48 0zM120 256a24 24 0 1 1 48 0 24 24 0 1 1 -48 0zm0-96a24 24 0 1 1 48 0 24 24 0 1 1 -48 0zm0 192a24 24 0 1 1 48 0 24 24 0 1 1 -48 0z"/></svg>',
};

export { IconClock };

export { default as IconBitcoin } from '~icons/fa6-brands/bitcoin';
export { default as IconGithub } from '~icons/fa6-brands/github';

export { default as IconArrowDown } from '~icons/fa6-solid/arrow-down';
export { default as IconArrowRightArrowLeft } from '~icons/fa6-solid/arrow-right-arrow-left';
export { default as IconArrowRightFromBracket } from '~icons/fa6-solid/arrow-right-from-bracket';
export { default as IconArrowRightToBracket } from '~icons/fa6-solid/arrow-right-to-bracket';
export { default as IconArrowUp } from '~icons/fa6-solid/arrow-up';
export { default as IconChartPie } from '~icons/fa6-solid/chart-pie';
export { default as IconCircleExclamation } from '~icons/fa6-solid/circle-exclamation';
export { default as IconCircleQuestion } from '~icons/fa6-solid/circle-question';
export { default as IconCloud } from '~icons/fa6-solid/cloud';
export { default as IconCubes } from '~icons/fa6-solid/cubes';
export { default as IconDiagramProject } from '~icons/fa6-solid/diagram-project';
export { default as IconEthernet } from '~icons/fa6-solid/ethernet';
export { default as IconHardDrive } from '~icons/fa6-solid/hard-drive';
export { default as IconHelmetSafety } from '~icons/fa6-solid/helmet-safety';
export { default as IconLayerGroup } from '~icons/fa6-solid/layer-group';
export { default as IconListOl } from '~icons/fa6-solid/list-ol';
export { default as IconMask } from '~icons/fa6-solid/mask';
export { default as IconMoon } from '~icons/fa6-solid/moon';
export { default as IconNetworkWired } from '~icons/fa6-solid/network-wired';
export { default as IconRoute } from '~icons/fa6-solid/route';
export { default as IconServer } from '~icons/fa6-solid/server';
export { default as IconShieldHalved } from '~icons/fa6-solid/shield-halved';
export { default as IconSpinner } from '~icons/fa6-solid/spinner';
export { default as IconSun } from '~icons/fa6-solid/sun';
export { default as IconTable } from '~icons/fa6-solid/table';
export { default as IconTriangleExclamation } from '~icons/fa6-solid/triangle-exclamation';
export { default as IconUserGroup } from '~icons/fa6-solid/user-group';
export { default as IconUserSecret } from '~icons/fa6-solid/user-secret';

export { default as IconTorProject } from '~icons/simple-icons/torproject';
